name: bot
on:
  push:
    paths: [data.xlsx]
  workflow_dispatch:
concurrency:
  group: bot
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 355
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          TEAMS_URL: ${{ secrets.TEAMS_URL }}
